# Site settings
title: DIORAMA
email: contact@diorama.io
description: > # this means to ignore newlines until "baseurl:"
  Diorama description

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.diorama.io/" # the base hostname & protocol for your site
twitter_username:
github_username:  diorama

# Build settings
markdown: kramdown
